stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src/github.com/redsky2017
        ln -s `pwd` /go/src/github.com/redsky2017/pipeline-example-go
        cd /go/src/github.com/redsky2017/pipeline-example-go
        go build -o bin/go-hello-server
        go test -cover
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: go-helloserver:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
