kind: Service
apiVersion: v1
metadata:
  name: gohelloserver-service
spec:
  selector:
    app: gohelloserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-helloserver
  labels:
    app: gohelloserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gohelloserver
  template:
    metadata:
      labels:
        app: gohelloserver
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: gohelloserver
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
